name: lauraundthierry
favicon: null
layout_spectrum: 0.07401675009168684
typography_spectrum: 0.4380769713316113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7746245341841131
  lightness: 0.6150106103159487
  saturation: 0.2113538384437561
  rhythmicContrast: 0.1606617826037109
purpose: []
